name: Conditions Workflow
on: [push]
jobs:
  conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Run in a condition
        if: github.ref == 'refs/heads/main1'
        run: echo This runs in a condition
