name: Conditions Workflow
on: [push]
jobs:
  conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Run in a condition
        if: "${{ github.ref_name == 'main' }}"
        run: echo This runs in a condition
