name: Context variables Demo
on: workflow_dispatch
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Display actor and ref
        run: echo "This job is triggered by ${{github.actor}} on branch ${{github.ref_name}}"
      - name: Print Github Context
        run: echo "${{toJson(github)}}"
      - name: Get short SHA
        id: short_sha
        run: echo "SHA ${GITHUB_SHA::7}"
      - name: Print all environment variables
        run: printenv

