name: This is if demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "Running build task"
          echo "${{ toJson(github.event_name) }}"
      
