name: This is if demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome step
        # if: github.ref == 'refs/heads/main'
        run: hari Welcome to this step
      - name: Welcome step2
        if: always()
        run: echo "Welcome to step2"
      
