name: This is if demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
      - name: Step Two
        if: ${{ steps.step1.outputs.version == '0.0.1' }}
        run: echo "Welcome to Step Two"
      
