name: This is a demo
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "Running build task"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.event.pull_request.head.ref }}"
      
