name: This is a demo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        # if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "Running build task"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.head_ref }}"
      
