name: This is if demo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Running build task"
  deploy:
    runs-on: ubuntu-latest
    if: "${{ github.ref_name == 'develop' }}"
    steps:
      - name: Deploy step
        run: echo "Deploying the app"
      
