name: Workflow with env
on:
  workflow_dispatch:
env:
  MY_NAME: "Java Home"
jobs:
    demo:
      runs-on: ubuntu-latest
      env:
        MY_NAME: "JHC"
      steps:
        - name: Print Name
          run: echo "Hello $MY_NAME Welcome! "
