name: Next Deploy Job
on:
  workflow_dispatch:
jobs:
  quality_check:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Check Code Quality
        run: |
          echo "Checking code quality..."
          # exit 1
          
  dev_deploy:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Dev Deploy
        run: echo "Deploying to dev..."

  success_email:
    needs: ['dev_deploy','quality_check']
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: send failure alert
        run: echo " dev_deploy Result - ${{ needs.dev_deploy.result }}"

  failure_email:
    needs: ['dev_deploy','quality_check']
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: send failure alert
        run: echo "Alerting team about failure"
    
