name: Next Deploy Job
on:
  workflow_dispatch:
jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Quality
        run: |
          echo "Checking code quality..."
          exit 1
  edev_deploy:
    runs-on: ubuntu-latest
    needs: quality_check
    steps:
      - name: Dev Deploy
        run: echo "Deploying to dev..."

  failure_email:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: send failure alert
        run: echo "Alerting team about failure"
    
