name: Next Deploy Job
on:
  workflow_dispatch:
jobs:
  quality_check:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Check Code Quality
        run: |
          echo "Checking code quality..."
          exit 1
  dev_deploy:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    needs: quality_check
    steps:
      - name: Dev Deploy
        run: echo "Deploying to dev..."

  success_email:
    needs: dev_deploy
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: send failure alert
        run: echo "Alerting team about failure"
    
