name: Outputs Demo
on: push
jobs:  
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: mystep
        run: echo "app_version=1.2.3 >> $GITHUB_OUTPUT"
      - name: Print Output
        run: echo "${{ steps.mystep.outputs.app_version }}"
    
