name: Outputs Demo
on: workflow_dispatch
jobs:  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        id: step1
        run: echo "name=Hari Kammana" >> $GITHUB_OUTPUT
      - name: Step Two
        run: echo "${{ steps.step1.outputs.name }}"
