name: Outputs Demo
on: push
jobs:  
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        id: step1
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT
      - name: Step Two
        run: echo "The output of step1 is ${{ steps.step1.outputs.version }}"
    
