name: Outputs Demo
on: push
jobs:  
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: "${{ steps.step1.outputs.name }}"
    steps:
      - name: Step One
        run: echo "name=Java Home Cloud" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print output of Job1
        run: echo "$${{ needs.job1.outputs.output1 }}"
    
