name: Reusable workflow
on:
  workflow_call:
    inputs:
      name:
        type: string
        description: Enter your name
jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello ${{inputs.name}}, Welcome!"
