name: TF Deploy
on: workflow_dispatch
jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: TF Setup
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.12.2
      - name: Test tf version
        run: terraform --version
